os: linux
dist: focal
language: python
python:
  - "3.8"
addons:
  sonarcloud:
    organization: $SONAR_ORG_KEY
    token: ${SONAR_TOKEN}
install:
  - pip install flask pytest flask-wtf coverage
script:
  - coverage run -m pytest test.py || travis_terminate 1;
  - coverage xml app.py || travis_terminate 1;
  - sonar-scanner || travis_terminate 1;
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: $HEROKU_APP_NAME
  on:
    branch: main